### ISSUE TITLE
Can we use this gem on Heroku?

### ISSUE THREAD

**Issue by ravi-we** [ricn/libreconv#13]
Hi Guys,

I need to use libreconv gem in one of my current project which is hosted on Heroku Cader 14. I used https://github.com/rishihahs/heroku-buildpack-libreoffice to support libreoffice on Heroku but getting following error while using gem's features:

"IOError: (Can't find LibreOffice or OpenOffice executable)"

Can anyone help me please to fix this issue on Heroku.

Thanks

**Comment by ricn** [comment]
Hi,

I guess Heroku does not put the soffice binary in the PATH. If you know the path to the soffice binary on Heroku you can specify it when doing the conversion:

Libreconv.convert('document.docx', '/Users/ricn/pdf_documents', '/path/to/soffice')

**Comment by ravi-we** [comment]
Thanks Richard! It worked (y)

**Comment by dsmithco** [comment]
ravi-we, what was the path that you used to get this to work on heroku?

**Comment by vkeziah** [comment]
@ravi-we  what was the path that you used to get this to work on heroku?

**Comment by itayariely** [comment]
Someone has found a solution to this problem?

**Comment by vkeziah** [comment]
what is the soffice path on heroku ? @ravi-we @ricn

**Comment by itayariely** [comment]
@vkeziah did you figure it out

**Comment by 17100262** [comment]
Libreconv gem does not create temp file on heroku. It gives me following error
No such file or directory @ rb_sysopen - /app/tmp/d20180119-4-1n9jguq/Employee_Promotion.pdf

Can anyone help me with this?
